.TH scm-workbench 1 "27 Jul 2016" "" "scm-workbench man page"
.SH NAME
scm-workbench

.SH SYNOPSIS
SCM Workbench is a GUI to easily work with Git, Mercurial (hg) and Subversion (svn) repositories.

.SH DESCRIPTION
SCM Workbench is a GUI to easily work with Git, Mercurial (hg) and Subversion (svn) repositories.

.SH OPTIONS
TBD

.SH BUGS
Please report any bugs on https://github.com/barry-scott/scm-workbench.

.SH AUTHOR
Barry Scott (barry@barrys-emacs.org)
