.TH scm-workbench 1 "27 Jul 2016" "" "scm-workbench man page"
.SH NAME
scm-workbench-git-callback \- Source Code Management Wokrkbench

.SH SYNOPSIS
scm-workbench-git-callback is a git helper for scm-workbench.

.SH DESCRIPTION
scm-workbench-git-callback is a git helper for scm-workbench.

.SH BUGS
Please report any bugs on https://github.com/barry-scott/scm-workbench.

.SH AUTHOR
Barry Scott (barry@barrys-emacs.org)
